name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~1.5

      - name: Terraform Version
        run: terraform -version

      - name: Install terraform-docs
        run: |
          WORK_DIR=$(mktemp -d)
          curl -Lo ${WORK_DIR}/terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.18.0/terraform-docs-v0.18.0-$(uname)-amd64.tar.gz
          cd ${WORK_DIR}
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mv terraform-docs /usr/local/bin/terraform-docs
      - name: Generate docs
        run: make docs

      - name: Check git diff is clean (all files generated should be committed)
        run: git diff --exit-code

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.51.1
      - name: Terraform Lint
        run: make lint

      - name: Terraform Validate
        run: make validate
